apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-risf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-risf
  template:
    metadata:
      labels:
        app: hello-risf
    spec:
     # securityContext:
     #   runAsUser: 101
     #   runAsGroup: 101
     #   fsGroup: 101
      containers:
      - name: nginx
     #   securityContext:
     #     allowPrivilegeEscalation: false
     #     capabilities:
     #       drop: ["ALL"]
        image: hello-risf:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-risf-service
spec:
  selector:
    app: hello-risf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
