apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-itsf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-itsf
  template:
    metadata:
      labels:
        app: hello-itsf
    spec:
      securityContext:
        runAsUser: 101  # UID de nginx
        fsGroup: 101
      initContainers:
      - name: init-html
        image: alpine
        command: ["sh", "-c", "cp /tmp/index.html /usr/share/nginx/html/ && chmod 644 /usr/share/nginx/html/index.html"]
        volumeMounts:
        - name: config-volume
          mountPath: /tmp
        - name: html-volume
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:stable-alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume
        configMap:
          name: itsf-html-config
      - name: html-volume
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: hello-itsf-service
spec:
  selector:
    app: hello-itsf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
