apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-itsf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-itsf
  template:
    metadata:
      labels:
        app: hello-itsf
    spec:
      initContainers:
      - name: init-html
        image: alpine
        command: ['sh', '-c', 'echo "<h1>HELLO ITSF</h1>" > /usr/share/nginx/html/index.html']
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "chmod 644 /usr/share/nginx/html/index.html"]
      
      volumes:
      - name: html-volume
        persistentVolumeClaim:
          claimName: itsf-html-claim
      - name: fallback-volume
        emptyDir: {}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: itsf-html-volume
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/itsf-html"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itsf-html-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  volumeName: itsf-html-volume

---
apiVersion: v1
kind: Service
metadata:
  name: hello-itsf-service
spec:
  selector:
    app: hello-itsf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
